var angular = require("angular");
require("angular-translate");
require("angular-translate-loader-static-files");
require("lodash");
var app = angular.module("firstApp", ['pascalprecht.translate']);
require('./app/configs/translateConfig')(app);
require('./app/services/dataServices/dataService')(app);
require('./app/components/mainComponent/mainComponent')(app);
require('./app/components/adderComponent/addListComponent')(app);
require('./app/components/listComponent/stringListComponent')(app);
require('./app/filters/digitFilter')(app);