require("angular");
require("angular-mocks");
require('./app/styles/style.css');
var angular = require("angular");
var app = angular.module("firstApp", ['pascalprecht.translate']);
require("angular-translate");
require("angular-translate-loader-static-files");
require("lodash");
require('./app/configs/translateConfig')(app);
require('./app/services/languageService')(app);
require('./app/services/dataService')(app);
require('./app/components/mainComponent/mainComponent')(app);
require('./app/components/inputComponent/inputComponent')(app);
require('./app/components/outputComponent/outputComponent')(app);
require('./app/components/settingComponent/settingComponent')(app);
require('./app/components/listFilterComponent/listFilterComponent')(app);
require('./app/filters/digitFilter')(app);
